Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
numero:inteiro
antecessor:inteiro
sucessor:inteiro
Inicio
escreva("Numero: ")
leia(numero)
antecessor<-numero -1
sucessor<- numero +1
escreval(antecessor," ",numero," ",sucessor)
Fimalgoritmo