Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
numero1:vetor[1..10] de inteiro
contador:inteiro

Inicio
para contador de 1 ate 10 faca
     escreva("escreva um numero: ")
     leia(numero1[contador])
fimpara
para contador de 1 ate 10 faca
     escreval(numero1[contador])
fimpara


Fimalgoritmo