Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
celsius:real
fah: real


Inicio
escreval("Converter Grau celsius para graus Fahrenheit")
escreva("Grau celsius= ")
leia(celsius)
fah<-(9*celsius+160)/5
escreval(celsius," para fahrenheit =",fah)
Fimalgoritmo