Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
f,c:real
Inicio
escreval("Graus Fahrenheit para graus celsius")
escreva("graus Fahrenheit =")
leia(f)
c<-(f-32)*(5/9)
escreval("Fahrenheit para celsius fica= ",c)


Fimalgoritmo