Algoritmo "semnome"

Var
nome1: caractere
pessoa1: caractere
pessoa2: caractere
pessoa3: caractere
pessoa4: caractere
sobrenome1: caractere
data_n1: inteiro
data_n2: inteiro
velocidade_veiculo:inteiro
tempo_veiculo:real

velocidade_ms:real
n1:real
n2:real
n3:real
n4:real
impar_par:real
altura1:real
altura2:real
Inicio
escreva("Digite o seu nome: ")  //1 atividade
leia(nome1)
escreva("Digite o seu sobrenome: ")
leia(sobrenome1)
escreval("Prazer em conhecê-lo ",nome1," ",sobrenome1)

Fimalgoritmo