Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/08/2020
Var
numb:inteiro
numA:inteiro
numC:inteiro
Inicio
escreva("Primeiro numero: ")
leia(numA)
escreva("Segundo numero: ")
leia(numB)
numC<- numA
numA<- numB
numB<- numC
escreva(numA," e",numB)
Fimalgoritmo